RA-03 верстка кнопок в нижней части экрана
jybo84/AndroidStudy pull request #1
Opened 2024-03-06 05:19 UTC by jybo84

2024-03-06 05:28 UTC, jybo84 commented
Иван можно сразу возникающие вопросы.

2024-03-06 05:30 UTC, jybo84 commented
1. ImageView в верхней части экрана отображается только на 80%. match_parent не отрабатывает. Растянул ее при помощи scaleType: fitXY но тогда теряется четкость самой картинки. Как растянуть картинку без потери качества?

2024-03-06 05:32 UTC, jybo84 commented
2. Как текст "избранное" в самой кнопке поднять. Когда применяю padding у меня пол текста исчезает.

2024-03-06 05:33 UTC, jybo84 commented
3. как расстояние от слова "избранное" до иконки сердечка уменьшить?

2024-03-06 05:36 UTC, jybo84 commented
4. Как применить второй стиль к кнопке. Я уже создал стиль там атрибуты для текста. А второй стиль атрибуты для самой кнопки. Пришлось все атрибуты в один стиль засовывать.

2024-03-07 18:28 UTC, ievetrov requested changes

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
можешь рассказать зачем этот тег и как он работает?

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/iv_category-playstore.png
это изображение нам не нужно. оно тоже сгенерировано автоматически при импорте, но картинку в пнг просто нужно было перенести в drawable

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/res/font/montserrat_alternates.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
а почему ты решил грузить шрифты из сети? но логики загрузки не вижу. 
я все таки предлагаю импортировать шрифты по моему примеру из урока, особенно, пока мы только учимся (кроме того в ТЗ конкретно указано что нужно сделать)

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="45dp"
отступ считаем не до конца макета. кнопки на борде имитруют кнопки управления телефона

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
>          android:layout_width="wrap_content"
ширину контейнера правильнее сделать по ширине родителя. чтобы кнопки растянулись на весь экран. у самих кнопках следует сделать то же самое

2024-03-07 18:28 UTC, ievetrov commented on app/src/main/res/values/font_certs.xml
> +    <array name="com_google_android_gms_fonts_certs">
сертификаты? а зачем?

2024-03-09 11:11 UTC, jybo84 commented on app/src/main/res/font/montserrat_alternates.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
Почему то у меня не получается сделать так же как и на видео. 
на видео ты зашел в Andr.ResourseDirectory прописал название директории font выбрал тип font -> ок. И система сама тебе создала ссылку на скачанный файл. У меня же просто создается папка и все. 
Видео загрузил через вкладку Resourse Manager. И сразу этот шрифт появился в созданной папке.

2024-03-09 11:12 UTC, jybo84 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="45dp"
здесь куча вопросов и недопонимания. Вопросы со скринами скину в личку, что б было более понятно

2024-03-09 14:41 UTC, jybo84 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="45dp"
Все отбой. Вопрос решен

2024-03-10 09:47 UTC, ievetrov requested changes

2024-03-10 09:47 UTC, ievetrov commented on app/build.gradle.kts
> +    implementation("androidx.fragment:fragment-ktx:1.6.2")
в этом задании пока не занимаемся фрагментами. не нужно делать то, что не требуется (в этой ветке по крайней мере). велик шанс себя запутать

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
если не знаешь зачем это нужно, давай все таки убирать. в уроке по добавлению шрифтов такого не было

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/iv_category-playstore.png
https://gist.github.com/ievetrov/3d047ff055d8a1277fffdc0d8cdffd6c

это тоже сгенерированный ассет, который нам не нужен.
во вторых в этой задаче не требовалось верстать экран со списком категорий!

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/font/montserrat_alternates.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
> И система сама тебе создала ссылку на скачанный файл

никакую ссылку система не генерировала. я просто скопипастил скачанные шрифты с гугл фонтс из проводника в папку font и все.

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/font/montserrat_alternates.xml
> +<font-family xmlns:app="http://schemas.android.com/apk/res-auto"
шрифт скачивается в формате ttf. его и нужно копировать. этот файл удаляем

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        <com.google.android.material.button.MaterialButton
пусть обе кнопки создаются обычным тэгом Button

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="36dp"
Есть разные способы установки высоты. я прошу устанавливать высоту с помощью внутренних паддингов. поэтому пусть высота здесь будет по размеру контента

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/values/StyleNavButton.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
давай еще в стиль добавим all caps, а сам текст в ресурсах будет обычным. лучше программно стилизовать

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/values/colors.xml
> +    <color name="color_button_category">#525DC0</color>
color то в начале, то в конце. нужно выбрать какой-то один стиль и придерживаться его

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/values/font_certs.xml
> +    <array name="com_google_android_gms_fonts_certs">
удаляй этот файл и импортируй только файлы ttf. больше ничего не нужно

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/background_color</item>
отлично, посмотри еще как стилизовать навбар (с кнопками) по такой же аналогии

2024-03-10 09:47 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="android:paddingVertical">5dp</item>
у кнопок ставим только паддинг по вертикали. и он равен 10 по макету

2024-03-11 10:34 UTC, ievetrov requested changes

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginHorizontal="16dp"
Все значения размеров и цветов выносим в ресурсы. Будем брать оттуда и переиспользовать

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/values/StyleNavButton.xml
> +        <item name="android:paddingVertical">10dp</item>
- здесь актуален только паддинг по вертикали, другие не нужны. 
- все размеры выносим в ресурсы

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="iv_picture">iv_picture</string>
Неясно зачем это значение здесь

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +        <item name="android:textColor">#FFFFFF</item>
цвета и размеры берем из ресурсов

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/values/style.xml
> +
пустая строка осталась

2024-03-11 10:34 UTC, ievetrov commented on app/src/main/res/values/StyleNavButton.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
А, ну и стиль перенеси в файл со стилями. отдельный XML для этого не нужен

2024-03-12 10:03 UTC, ievetrovdev approved these changes

2024-03-12 10:58 UTC, merged