RA-11 экран со списком рецептов
jybo84/AndroidStudy pull request #13
Opened 2024-04-11 10:56 UTC by jybo84

2024-04-11 14:03 UTC, ievetrovdev requested changes

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <ImageView
ContentDescription в Android — это описание элементов интерфейса для пользователей с ограничениями зрения, использующих средства чтения с экрана, например, TalkBack. Он важен для интерактивных элементов (кнопок, ссылок), чтобы объяснить их функции. Для декоративных элементов можно установить "@null", чтобы они игнорировались средствами чтения. Отсутствие contentDescription может сделать приложение недоступным для пользователей с нарушениями зрения.

Предлагаю тут добавить описание контента изображения. Причем задавать динамически в зависимости от переданного во фрагмент заголовка. Текст должен быть развернутым, например, "Изображение для ...”

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_height="224dp">
не вынесено в ресурсы

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/item_recipes.xml
> +<?xml version="1.0" encoding="utf-8"?>
так как это лейаут для элемента списка (одного), то и название лейаута должно быть в единственном числе

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/item_recipes.xml
> +            android:layout_height="32dp"
размеры, стили и т д. все выносим в ресурсы. всегда.

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
>      <string name="hello_blank_fragment">Hello blank fragment</string>
эта строка тут не нужна кажется

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_marginHorizontal="@dimen/recycle_view_and_card_view_margin_horizontal_and_vertical"
дубли ресурсов. 
обсуждали вроде насколько помню это уже достаточно подробно. переиспользуй готовые ресурсы и не плоди дубли

<img width="787" alt="Снимок экрана 2024-04-11 в 16 58 05" src="https://github.com/jybo84/AndroidStudy/assets/153023186/e6ea64dd-7a53-4a27-984e-0c56f8bae6d3">

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +    fun openRecipeByRecipeId(id: Int) {
метод нигде не вызывается (см. тз)

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        val adapter = RecipesListAdapter(STUB.getRecipesByCategoryId(categoryId))
инициализацию адаптера предлагаю вынести в отдельный метод

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        categoryId = arguments?.getInt("ARG_CATEGORY_ID")
как и инициализацию аргументов. 

нужно onViewCreated сделать чистым методом и  вызывать здесь только вспомогательные методы

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:text="@string/title_burgers"
это значение приходит из базы и его не нужно хардкодить. вынесем название в tools

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:layout_marginTop="164dp"
оптимальнее приклеить текст к левой и нижней граням. для этого уже есть стандартные отступы у тебя в ресурсах

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <TextView
Если текст будет слишком большой, то может располагаться вплотную к правой границе или вовсе вылезет за пределы экрана. Так как мы находимся внутри констрейнта, есть пара хитрых атрибутов, чтобы это реализовать более элегантно. Не забудь добавить констрейнт справа и все протестировать
app:layout_constrainedWidth="true"
app:layout_constraintHorizontal_bias="0.0"

2024-04-11 14:03 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:layout_width="124dp"
название может быть разной длины. не нужно хардкодить ширину, пусть будет по размеру контента

2024-04-11 21:48 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <ImageView
Исправлено

2024-04-11 21:53 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_height="224dp">
Исправлено

2024-04-11 21:54 UTC, jybo84 commented on app/src/main/res/layout/item_recipes.xml
> +<?xml version="1.0" encoding="utf-8"?>
Исправлено

2024-04-11 22:09 UTC, jybo84 commented on app/src/main/res/layout/item_recipes.xml
> +            android:layout_height="32dp"
Исправлено

2024-04-11 22:27 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        val adapter = RecipesListAdapter(STUB.getRecipesByCategoryId(categoryId))
Исправлено

2024-04-11 22:30 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:text="@string/title_burgers"
Исправлено

2024-04-11 23:48 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:layout_width="124dp"
Исправлено

2024-04-11 23:48 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <TextView
Исправлено. Протестировано.

2024-04-11 23:55 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:layout_marginTop="164dp"
Исправлено

2024-04-11 23:56 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +    fun openRecipeByRecipeId(id: Int) {
Исправлено

2024-04-12 00:01 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            android:text="@string/title_burgers"
При использовании tools, ломается. Не приходят сюда значения

2024-04-12 00:44 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_marginHorizontal="@dimen/recycle_view_and_card_view_margin_horizontal_and_vertical"
Исправлено

2024-04-12 01:13 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        categoryId = arguments?.getInt("ARG_CATEGORY_ID")
Исправлено

2024-04-12 10:08 UTC, ievetrovdev requested changes

2024-04-12 10:08 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        binding.tvCategory.text = categoryName
верно, передаем название категории из аргументов

но также еще надо инициализировать изображение категории и тоже программно. доставай categoryImageUrl, обращайся к ассетам и присваивай изображение для вьюхи

2024-04-12 10:08 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +        categoryId = arguments?.getInt("ARG_CATEGORY_ID")
Хорошо, ключи для аргументов принято выносить общие константы проекта в отдельный файл. Его можно назвать, например, Constants.kt и переиспользовать оттуда в разных местах, где это требуется.

2024-04-14 06:24 UTC, ievetrovdev approved these changes

2024-04-14 06:24 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/Constants.kt
> +const val ID = "ARG_CATEGORY_ID"
Хорошо, но на будущий ПР

название переменной лучше сделать `ARG_CATEGORY_ID`
а вот значение принято обычно принято писать в нижнем регистре `arg_category_id`

2024-04-14 06:24 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +            // get input stream
лишние комментарии лучше не оставлять, в данном случае как мне кажется особого смысла они не несут

2024-04-14 06:24 UTC, ievetrovdev commented on app/src/main/res/layout/item_recipe.xml
> +        <TextView
добавь еще отступы для текствью как по макету, чтобы текст не прилипал к стенкам контейнера. реализовать можно через марджин у текста или через паддинг у контейнера

2024-04-14 09:55 UTC, merged