RA-13 реализация экрана рецепта без механизма подсчета
jybo84/AndroidStudy pull request #15
Opened 2024-04-17 11:30 UTC by jybo84

2024-04-19 07:19 UTC, ievetrovdev requested changes
А также
- шрифты в ингредиентах и способе приготовления не соответствуют макета

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/Constants.kt
> +const val ARG_RECIPE_IMAGE = "recipeImageUrl"
почему-то в другом стиле значение для изображения рецепта?

<img width="793" alt="Снимок экрана 2024-04-19 в 10 29 13" src="https://github.com/jybo84/AndroidStudy/assets/153023186/ef0bb4dc-b6b9-4a90-bf11-e9df1953d650">

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +
лишние пустые строки в файле - надо привести в порядок и следить за аккуратностью

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="ingr_accaunt">%1$s %2$s</string>
опечатка?

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="title_ingredients">ингридиенты</string>
опечатка

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                    android:textSize="20sp"
хардкод

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                    android:textSize="20sp"
также используй стили для оформления текстовых блоков с одинаковыми атрибутами (у тебя есть стиль, но тут остались атрибуты оформления)

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                    android:textStyle="bold" />
корректнее импортировать соответствующий шрифт, а не добавлять атрибуты жирности (могут не работать или не соответствовать параметрам макета)

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/IngredientsAdapter.kt
> +//class IngredientsAdapter(private val dataSet: List<Ingredient>): RecyclerView.Adapter<IngredientsAdapter.ViewHolder>() {
остался комментированный код

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                tools:listitem="@layout/item_ingredient" />
Каждый элемент item_ingredient у тебя является карточкой, что не оч корректно. Тут карточки больше вообще не нужны, тк некорректно ставятся разделители (разделитель и обводка карточки сливаются)

давай так
- в карточке обычный линеар будет
- а белый фон для всего списка сделаем у самого тэга RecyclerView

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/res/layout/item_cooking_method.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
про метод аналогичные замечания

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +        val dividerItemIngredients = DividerItemDecoration(binding.rvIngredients.context, RecyclerView.VERTICAL)
Хорошо, ты используешь DividerItemDecoration. Но есть проблема – он проставляет разделитель после последнего элемента, а также чуть сложнее будет добавлять отступы по бокам (согласно макету).

Решение. Предлагаю использовать разделитель из Material библиотеки – MaterialDividerItemDecoration. 

Он умеет:
- применять проперти isLastItemDecorated, установив которому значение false – не будет отрисовывать последний разделитель. 
- устанавливать отступы слева и справа с помощью пропертей dividerInsetStart и dividerInsetEnd
- ему не требуется отдельный drawable, достаточно задать только цвет через проперти dividerColor

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +        val dividerItemIngredients = DividerItemDecoration(binding.rvIngredients.context, RecyclerView.VERTICAL)
вместо контекста вьюхи, корректнее будет передавать контекст через метод фрагмента requireContext()

2024-04-19 07:19 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/IngredientsAdapter.kt
> +
пустая строка

2024-04-19 08:35 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/Constants.kt
> +const val ARG_RECIPE_IMAGE = "recipeImageUrl"
Исправлено.

2024-04-19 08:37 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipe.xml
> +
Исправлено.

2024-04-19 08:40 UTC, jybo84 commented on app/src/main/res/values/strings.xml
> +    <string name="ingr_accaunt">%1$s %2$s</string>
Исправлено.

2024-04-19 08:42 UTC, jybo84 commented on app/src/main/res/values/strings.xml
> +    <string name="title_ingredients">ингридиенты</string>
Нет. Вроде норм все.

2024-04-19 08:48 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/IngredientsAdapter.kt
> +//class IngredientsAdapter(private val dataSet: List<Ingredient>): RecyclerView.Adapter<IngredientsAdapter.ViewHolder>() {
Исправлено.

2024-04-20 12:08 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/IngredientsAdapter.kt
> +
Исправлено.

2024-04-20 12:15 UTC, jybo84 commented on app/src/main/res/layout/item_cooking_method.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
Иван, вот смотри,  как только я убираю cardView и ставлю LinearLyout то в конечном итоге на эмуляторе пропадают разделители.

2024-04-20 12:26 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipe.xml
> +                tools:listitem="@layout/item_ingredient" />
Иван, вот смотри, как только я убираю cardView и ставлю LinearLyout то в конечном итоге на эмуляторе пропадают разделители.

2024-04-20 12:27 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/IngredientsAdapter.kt
> +//class IngredientsAdapter(private val dataSet: List<Ingredient>): RecyclerView.Adapter<IngredientsAdapter.ViewHolder>() {
Исправлено.

2024-04-21 07:36 UTC, jybo84 commented on app/src/main/res/values/strings.xml
> +    <string name="title_ingredients">ингридиенты</string>
Исправлено.

2024-04-21 08:21 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipe.xml
> +                    android:textStyle="bold" />
Исправлено.

2024-04-21 08:25 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +        val dividerItemIngredients = DividerItemDecoration(binding.rvIngredients.context, RecyclerView.VERTICAL)
Ну да, здесь наверное больше информации нужно.

2024-04-21 08:49 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +        val dividerItemIngredients = DividerItemDecoration(binding.rvIngredients.context, RecyclerView.VERTICAL)
Странно именно про MaterialDividerItemDecoration на ютуб вообще ничего нет

2024-04-21 19:48 UTC, ievetrovdev requested changes

2024-04-21 19:48 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +    <LinearLayout
Как будто здесь лишнее вложение, можно убрать

2024-04-21 19:48 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +            tools:text="5 штук" />
В модели данных под единицу измерения есть отдельное поле. Его лучше сделать отдельной вью

2024-04-21 19:48 UTC, ievetrovdev commented on app/src/main/res/layout/item_ingredient.xml
> +            android:textSize="14sp"
Выносим в ресурсы и стили тут и везде где еще не вынесено

2024-04-21 19:48 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:backgroundTint="@color/white"
Как видишь этот атрибут не подействовал. Попробуй android:background. И не забудь про скругления углов

2024-04-21 22:58 UTC, jybo84 commented on app/src/main/res/layout/item_ingredient.xml
> +    <LinearLayout
Исправлено.

2024-04-21 23:14 UTC, jybo84 commented on app/src/main/res/layout/item_ingredient.xml
> +            android:textSize="14sp"
Исправлено

2024-04-21 23:33 UTC, jybo84 commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:backgroundTint="@color/white"
Исправлено.

2024-04-22 00:36 UTC, jybo84 commented on app/src/main/res/layout/item_ingredient.xml
> +            tools:text="5 штук" />
Исправлено.

2024-04-22 14:20 UTC, ievetrovdev approved these changes

2024-04-22 22:08 UTC, merged