RA-04 работа с пустым стартовым фрагментом
jybo84/AndroidStudy pull request #2
Opened 2024-03-13 04:48 UTC by jybo84

2024-03-13 11:31 UTC, ievetrov requested changes

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +    private var binding: FragmentListCategoriesBinding? = null
Предлагаю использовать backing property, реализованный в уроке.

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
Ты используешь Java метод add из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 
Именно для импорта этого метода add() нужно было имплементировать библиотеку fragment-ktx. 
Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
lateinit - заманчивая конструкция, но опасная и никак не спасающая от NullPointerException. Вот тут Кирилл Розов наглядно объясняет почему лучше избежать использования lateinit по возможности. https://youtu.be/0nXXUzMyF8c

Лучше стараться продумать подходящее поведение по-умолчанию. В уроке я реализовывал backing property (резервное свойство). Но здесь предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +    private lateinit var fragmentTransaction: FragmentTransaction
можно не выносить создание этой переменной, если будешь использовать более актуальный подход из доки.

https://developer.android.com/guide/fragments/create#add-programmatic

<img width="903" alt="Снимок экрана 2024-03-13 в 15 20 39" src="https://github.com/jybo84/AndroidStudy/assets/34489023/60c69cb0-5f76-4558-88b4-0fdb454a4715">

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/drawable/shape_rectangle_top.xml
> +<?xml version="1.0" encoding="utf-8"?>
не понимаю для чего этот файл (он не понадобится)

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="@+id/linearLayout"
Почти да, контейнер будет отображать экран до кнопок. значит прикрепляем к контейнеру кнопок

        app:layout_constraintBottom_toTopOf="@+id/linearLayout"

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/button_category"
предлагаю айдишники записывать в стиле camel case

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
>      <dimen name="button_layout_margin_start">2dp</dimen>
Повторять одни и те же значения с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="fragment_container_margin_bottom">497dp</dimen>
ниже все размеры использоваться не будут (кроме 16). все остальное устанавливается адаптивно по размеру контента или экрана

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="text__top_rectangle_category">категории</string>
с двойным подчеркиванием подряд snake case никогда не пишут

2024-03-13 11:31 UTC, ievetrov commented on app/src/main/res/values/strings.xml
> +    <string name="text__top_rectangle_category">категории</string>
Обрати внимание, что на кнопке точно такой же текст. Лучше не дублировать значения, а переиспользовать уже имеющуюся строку. Только для идентификатора этой единой строки корректнее сделать какое-то более общее название. Например, так title_categories.

2024-03-13 12:05 UTC, jybo84 commented on app/src/main/res/values/strings.xml
> +    <string name="text__top_rectangle_category">категории</string>
Исправлено. Сделан один стиль для 3-х надписей (2 кнопки и TextView)

2024-03-13 12:17 UTC, jybo84 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="fragment_container_margin_bottom">497dp</dimen>
Исправлено. Лишнее убрано.

2024-03-13 12:19 UTC, jybo84 commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/button_category"
Исправлено. id изменены.

2024-03-13 12:25 UTC, jybo84 commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintBottom_toBottomOf="@+id/linearLayout"
Исправлено. Перезакрепленно

2024-03-14 00:41 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +    private var binding: FragmentListCategoriesBinding? = null
Исправлено. Применил

2024-03-14 02:44 UTC, jybo84 commented on app/src/main/res/values/dimens.xml
>      <dimen name="button_layout_margin_start">2dp</dimen>
Исправлено. В dimens убраны значения которые используются в разных местах.

2024-03-14 02:44 UTC, jybo84 commented on app/src/main/res/drawable/shape_rectangle_top.xml
> +<?xml version="1.0" encoding="utf-8"?>
Исправлено. Ликвидирован.

2024-03-14 02:53 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
ВРОДЕ удалось от java избавиться.

2024-03-14 02:53 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
С lazy что то пока не получается

2024-03-14 03:04 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
>      private lateinit var binding: ActivityMainBinding
Розов конечно хороший программист, но его видео не очень. Он прям сложно объясняет, куда-то сразу в дебри лезит. Его видео тяжело смотреть

2024-03-14 10:09 UTC, ievetrov requested changes

2024-03-14 10:09 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +    private var binding: FragmentListCategoriesBinding? = null
Только для активити, тут не вижу. Этот комментарий относится к 12 строке CategoriesListFragment конкретно, а не к чему-нибудь еще

2024-03-14 10:09 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +     private val binding by lazy{ActivityMainBinding.inflate(layoutInflater)}
не забывай про форматирование. видишь некрасиво - отступ лишний, пробелов нет. и еще лучше отбить пустой строкой перед методом ниже. все сливается

2024-03-14 10:09 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        val fragmentTransaction = supportFragmentManager.beginTransaction()
тоже не нужно делать вплотную. отступи пустой строкой

2024-03-14 10:09 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        fragmentTransaction.add(R.id.mainContainer, CategoriesListFragment()).commit()
> Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

не вижу изменений здесь. у тебя два параметра. просто возьми пример из доки, на нее я давал ссылку ранее и скриншот указал

Фрагмент для перехода тут в указан в качестве типа, а не параметра. Это важно

<img width="925" alt="Снимок экрана 2024-03-14 в 14 03 45" src="https://github.com/jybo84/AndroidStudy/assets/34489023/a224c99d-7576-4237-80a1-991d830d7fb0">

2024-03-14 10:09 UTC, ievetrov commented on app/src/main/res/layout/activity_main.xml
> +            android:textSize="16sp" />
размер текста
1. выносятся в ресурсы
2. в данном случае еще и можно положить в стиль шрифта кнопки

2024-03-14 12:42 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +     private val binding by lazy{ActivityMainBinding.inflate(layoutInflater)}
Исправлено. Ctrl- Alt- L

2024-03-14 12:43 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/MainActivity.kt
> +        val fragmentTransaction = supportFragmentManager.beginTransaction()
Исправлено.

2024-03-14 12:46 UTC, jybo84 commented on app/src/main/res/layout/activity_main.xml
> +            android:textSize="16sp" />
Исправлено. Перенесено

2024-03-17 15:18 UTC, ievetrov approved these changes

2024-03-18 01:05 UTC, merged