Ra 18 экран favourites
jybo84/AndroidStudy pull request #20
Opened 2024-05-02 13:15 UTC by jybo84

2024-05-04 04:41 UTC, ievetrovdev requested changes

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +        start()
Очень неконкретное название, лучше придерживаться ранее используемых паттернов. Оставь здесь вызов только двух методов метода: initUI и initRecycler.

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +    private fun openRecipesByCategoryId(categoryId: Int) {
при чем тут категории и рецептЫ?

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +            val category = STUB.getCategories().find {
делай как раньше делал - сначала создавай бандл, затем отдельно вызывай транзакцию с коммит лямбдой. не нужно усложнять визуально

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +     fun initUI() {
можешь объяснить это зачем делаешь? чего хотел добиться?

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favourites.xml
> +        android:id="@+id/tvHoth"
а что значит это слово?

2024-05-04 04:41 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favourites.xml
> +        style="@style/StyleTextNumberPortions"
стиль у заглушки другой

2024-05-04 09:00 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipeFragment.kt
> +     fun initUI() {
Исправлено. Пытался доступ к методу получить из другого класса.

2024-05-04 09:01 UTC, jybo84 commented on app/src/main/res/layout/fragment_favourites.xml
> +        android:id="@+id/tvHoth"
Исправлено. (Было рабочее название)

2024-05-04 09:11 UTC, jybo84 commented on app/src/main/res/layout/fragment_favourites.xml
> +        style="@style/StyleTextNumberPortions"
Исправлено

2024-05-04 09:23 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +        start()
Исправлено

2024-05-04 09:34 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +    private fun openRecipesByCategoryId(categoryId: Int) {
Исправлено.

2024-05-04 09:36 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +            val category = STUB.getCategories().find {
Иван, этот момент не очень понял

2024-05-04 09:51 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/FavouritesFragment.kt
> +            val category = STUB.getCategories().find {
Аааааа. Понял. Попробую поправить

2024-05-04 15:49 UTC, ievetrovdev requested changes

2024-05-04 15:49 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +            val recipeFragment = RecipesListFragment()
я имею в виду вынеси за лямбду все эти обращения к стабам, создание бандла итд. как ты раньше делал

<img width="701" alt="Снимок экрана 2024-05-04 в 19 44 01" src="https://github.com/jybo84/AndroidStudy/assets/153023186/e95f013c-2a2d-45b6-a48b-0bd0958e64d2">

2024-05-04 15:49 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +    var categoryId: Int? = null
тут тоже непонятное действие. напрямую из фрагмента во фрагмент мы нигде не обращаемся. только через передачу параметров в бандле

2024-05-04 15:49 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="color_empty_list">#666666</color>
дубль ресурса цвета!

2024-05-04 15:49 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favourites.xml
> +        style="@style/StyleSTUB"
ну так а сам шрифт будешь менять? повторяю, у текста заглушки другой стиль. не жирный

2024-05-05 01:19 UTC, jybo84 commented on app/src/main/res/values/colors.xml
> +    <color name="color_empty_list">#666666</color>
Исправлено

2024-05-05 01:42 UTC, jybo84 commented on app/src/main/res/layout/fragment_favourites.xml
> +        style="@style/StyleSTUB"
Исправлено

2024-05-05 01:44 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipesListFragment.kt
> +    var categoryId: Int? = null
Исправлено

2024-05-05 02:05 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +            val recipeFragment = RecipesListFragment()
Ага). Разобрался, понял

2024-05-05 11:41 UTC, ievetrovdev approved these changes

2024-05-05 11:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
> +        parentFragmentManager.commit {
во-1 пропало форматирование (отступы?)

2024-05-05 11:41 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/CategoriesListFragment.kt
>              replace(R.id.mainContainer, recipeFragment)
во-2 все в целом хорошо, но еще на будущее все таки рекомендую использовать метод replace не из стандртной библиотеки, а из fragment-ktx (которую импортировали в самом начале).

<img width="555" alt="Снимок экрана 2024-05-05 в 15 38 45" src="https://github.com/jybo84/AndroidStudy/assets/153023186/46fde632-371f-4d16-b2c5-2a2321b65fa6">

В этом случае есть ключевые отличия:
1. replace уже совсем другая функция – это экстеншн, который требует указания только типа фрагмента в <>, а не передачи ссылки на сам экземпляр через параметры. Это рекомендуемый в документации по фрагментам более современный подход.
2. Чтобы передать аргументы через бандл – нужно явно указать название аргументов args, иначе будет ошибка

В целом рекомендация на следующие ПР переделать все транзакции на такой способ

2024-05-05 11:55 UTC, merged