RA-20 ViewModel
jybo84/AndroidStudy pull request #21
Opened 2024-05-05 11:59 UTC by jybo84

2024-05-05 12:23 UTC, jybo84 commented
Иван, можешь посмотреть, по папкам файлы правильно раскиданы?

2024-05-05 12:23 UTC, jybo84 commented
Не очень понял п. 7 задания
Определить какие данные передаются на экран или изменяются. Для продуманной сущности внутри ViewModel создать data class с постфиксом State в названии.

2024-05-05 13:10 UTC, ievetrovdev commented
> Иван, можешь посмотреть, по папкам файлы правильно раскиданы?

RecipeViewModel будет исключительно для экрана с рецептом. Для других экранов будут тоже далее создадим свои вью модели

2024-05-05 13:12 UTC, ievetrovdev commented
> Не очень понял п. 7 задания Определить какие данные передаются на экран или изменяются. Для продуманной сущности внутри ViewModel создать data class с постфиксом State в названии.

Нужно понять что будет хранить состояние экрана. И из этих предположений создать отдельный класс для стейта внутри вью модели

2024-05-05 13:15 UTC, ievetrovdev requested changes

2024-05-05 13:15 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="favourite_heart">favouriteHeart</string>
а для чего эта фраза?
вообще у тебя часть ресурсов на англ, часть на русском. для локализации надо создать отдельный файл ресурсов с квалификатором языка, который у тебя будет вторым. давай приведем в порядок строки и удалим лишние непонятно какой смысл несущие для пользователя слова

2024-05-07 17:24 UTC, ievetrovdev requested changes

2024-05-07 17:24 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +//            recipeFragment.arguments = bundle
комментарии в проде не оставляем

2024-05-07 17:24 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeViewModel.kt
> +    private val _state = MutableLiveData(RecipeState())
Все создано верно, только давай объявление ЛД в самое начало класса вью модели перенесем

2024-05-07 17:24 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeViewModel.kt
> +        var recipe: Recipe? = null,
1. мы будем не изменять свойства, а копировать предыдущий стейт с изменением необходимых полей. поэтому пусть они все будут неизменяемые 
2. на экране еще динамически будет меняться количество ингредиентов - это свойство тоже предлагаю добавить и у него уже известно состояние по умолчанию

2024-05-08 00:41 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +//            recipeFragment.arguments = bundle
Исправлено

2024-05-08 00:42 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeViewModel.kt
> +    private val _state = MutableLiveData(RecipeState())
Исправлено

2024-05-08 00:55 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeViewModel.kt
> +        var recipe: Recipe? = null,
Исправлено

2024-05-08 16:35 UTC, ievetrovdev approved these changes

2024-05-11 06:17 UTC, merged