Ra 28 jetpack navigation
jybo84/AndroidStudy pull request #28
Opened 2024-05-29 06:25 UTC by jybo84

2024-05-30 21:23 UTC, danelyan requested changes

2024-05-30 21:23 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/MainActivity.kt
> +    private val nav by lazy { findNavController(R.id.mainContainer) }
давай не использовать короткие названия

2024-05-30 21:23 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/MainActivity.kt
> +    private val nav by lazy { findNavController(R.id.mainContainer) }
так и назови - navController

2024-05-30 21:23 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +//        parentFragmentManager.commit {
зачем тут закоменченный код?

2024-05-30 21:23 UTC, danelyan commented on app/src/main/res/layout/fragment_nav_host.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
это нужный файл?

2024-05-30 22:45 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/MainActivity.kt
> +    private val nav by lazy { findNavController(R.id.mainContainer) }
Да, согласен. Ты мне уже это говорил. Я себе даже записал и выделил. 
Исправил.

2024-05-30 22:45 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +//        parentFragmentManager.commit {
Исправил.

2024-05-30 22:48 UTC, jybo84 commented on app/src/main/res/layout/fragment_nav_host.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
Нужный или нет не знаю. Когда я создал класс NavHostFragment, то студия сама создала и этот файл. По идее она умная, создает только то что необходимо. Что б ничего не сломалось я его и не трогаю.

2024-05-31 05:37 UTC, danelyan approved these changes

2024-05-31 05:45 UTC, merged