RA-35 Retrofit
jybo84/AndroidStudy pull request #34
Opened 2024-06-20 04:07 UTC by jybo84

2024-06-23 04:28 UTC, danelyan requested changes

2024-06-23 04:28 UTC, danelyan commented on app/build.gradle.kts
> +
лишние пустые строки

2024-06-23 04:28 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/MainActivity.kt
> +
давай удалим из mainActivity все сетевые вызовы. Они нам тут не пригодятся

2024-06-23 04:28 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/listRecipe/RecipesListViewModel.kt
> +            _state.postValue( RecipeListState(
лишние пробел. Давай перенесем на новую строку RecipeListState

2024-06-23 04:28 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +        val recipeRepository = RecipesRepository()
репозиторий не нужно создавать тут, он должен быть во viewModel

2024-06-23 04:28 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +            adapterIngredient = IngredientsAdapter()
IngredientsAdapter() нужно создать и присвоить один раз, при инициализации UI с пустым списком ингридиентов.
А в подписке уже менять данные в адаптере и делать notifyDataSetChanges()

2024-06-23 04:28 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +            adapterCookingMethod = CookingMethodAdapter()
аналогично - адаптер создается один раз

2024-06-23 06:56 UTC, jybo84 commented on app/build.gradle.kts
> +
Исправлено

2024-06-24 04:30 UTC, danelyan requested changes

2024-06-24 04:30 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeViewModel.kt
> +                recipeRepository.getRecipeById(recipeId)?.method?.let { CookingMethodAdapter(it) }
тут ты делаешь сетевой запрос дважды. Тогда уже давай сделаем локальную переменную.
Однако - эти строки ввобще тут не нужны, они вроде ничего не делают

2024-06-24 04:30 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +            adapterIngredient?.dataSet = state.recipe?.ingredients ?: listOf()
да, так отлично

2024-06-24 04:43 UTC, danelyan approved these changes

2024-06-24 04:44 UTC, merged