RA-06 Генерация сущности локальной базы данных
jybo84/AndroidStudy pull request #4
Opened 2024-03-20 23:40 UTC by jybo84

2024-03-21 13:20 UTC, ievetrov requested changes

2024-03-21 13:20 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/Ingredient.kt
> +    val unitOfMeasure: String = "кг",
значений по умолчанию не делаем, у всех данных они будут разные

2024-03-21 13:20 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/Ingredient.kt
> +    val quantity: Double,
посмотри внимательнее на тип значения в JSON файле

2024-03-21 13:20 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/recipes.kt
> +        return categories
можно использовать короткую форму

2024-03-21 13:20 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/recipes.kt
> +            "assets/burger.png"
в мок данных лучше хранить только чистые данные. в каком каталоге проекта они лежат данным знать не обязательно

2024-03-21 23:37 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/Ingredient.kt
> +    val quantity: Double,
Там нет типа значения. Есть только само значение - 0.5, 2.0 ... Предположу что это значение Float так потребляет меньше памяти.

2024-03-21 23:38 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/Ingredient.kt
> +    val unitOfMeasure: String = "кг",
Исправлено.

2024-03-22 21:14 UTC, ievetrov requested changes

2024-03-22 21:14 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/Ingredient.kt
> +    val quantity: Float,
обрати внимание, что данные там указаны в двойных кавычках. а в таком виде всегда указывается только строка. дробное число (как и любое другое) указывалось бы без кавычек. а помнишь как указать тип Char?

2024-03-23 10:56 UTC, ievetrov approved these changes

2024-03-23 10:58 UTC, merged