RA-45 Внедрение Dagger.Hilt
jybo84/AndroidStudy pull request #44
Opened 2024-07-05 00:25 UTC by jybo84

2024-07-08 07:05 UTC, danelyan requested changes

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/data/Category.kt
> +data class Category @Inject constructor(
тут не нужен inject

2024-07-08 07:05 UTC, danelyan commented on build.gradle.kts
> +    id ("com.google.dagger.hilt.android") version "2.51.1" apply false
тут тоже можно alias сделать

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +    @delegate:Inject
- эта аннотация не нужна, если используешь by viewModels()
- поле можно приватным сделать

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/listRecipe/RecipesListFragment.kt
> +    @delegate:Inject
аннотация не нужна

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/favourites/FavouritesFragment.kt
> +    @delegate:Inject
аннотация не нужна

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/RecipesListAdapter.kt
> +            Drawable.createFromStream(
разве мы не используем теперь глайд? Давай грузить картинки не через ассетсы

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +    @delegate:Inject
аннотация не нужна

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/data/db/Converters.kt
> +        Gson().fromJson(value, Array<Ingredient>::class.java).toList()
замени Gson() на gson. Ты же его для чего-то создал выше

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/data/Recipe.kt
> +data class Recipe @Inject constructor(
этот Inject тут не нужен

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/data/Ingredient.kt
> +data class Ingredient @Inject constructor(
этот Inject тут не нужен

2024-07-08 07:05 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/RecipeModule.kt
> +    fun provideDataBase(): DataBase = DataBase.getDataBase(RecipesApplication.instance)
тут можно в методе `provideDataBase()` запросить контекст, то есть:
```Kotlin
    @Provides
    @Singleton
    fun provideDataBase(
        @ApplicationContext context: Context,
    ): DataBase = DataBase.getDataBase(context)
```

2024-07-08 23:01 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/data/Category.kt
> +data class Category @Inject constructor(
Исправлено

2024-07-08 23:04 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Исправлено

2024-07-08 23:05 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/recipe/RecipeFragment.kt
> +    @delegate:Inject
исправлено

2024-07-08 23:06 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/listRecipe/RecipesListFragment.kt
> +    @delegate:Inject
исправлено

2024-07-08 23:07 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/favourites/FavouritesFragment.kt
> +    @delegate:Inject
Исправлено

2024-07-08 23:08 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/category/CategoriesListFragment.kt
> +    @delegate:Inject
исправлено

2024-07-08 23:10 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/data/db/Converters.kt
> +        Gson().fromJson(value, Array<Ingredient>::class.java).toList()
исправлено

2024-07-08 23:10 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/data/Recipe.kt
> +data class Recipe @Inject constructor(
Исправлено

2024-07-08 23:11 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/data/Ingredient.kt
> +data class Ingredient @Inject constructor(
исправлено

2024-07-08 23:19 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/recipe/RecipesListAdapter.kt
> +            Drawable.createFromStream(
Исправлено

2024-07-08 23:28 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/RecipeModule.kt
> +    fun provideDataBase(): DataBase = DataBase.getDataBase(RecipesApplication.instance)
Исправлено

2024-07-08 23:28 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/ui/RecipesApplication.kt
>  class RecipesApplication : Application() {
Исправлено

2024-07-09 04:54 UTC, danelyan requested changes
1. Отсутствуют анимации при переключении Избранного и Категорий.
Можно через NavOptions задать:
```Kotlin
  binding.apply {
      buttonFavourites.setOnClickListener {
                navController.navigate(R.id.favouritesFragment,
                    null,
                    NavOptions.Builder()
                        .setEnterAnim(androidx.navigation.ui.R.anim.nav_default_enter_anim)
                        .build()
                )
      }
```

2. Давай добавим своих анимаций в ресурсы:
<img width="240" alt="Screenshot 2024-07-09 at 07 48 36" src="https://github.com/jybo84/AndroidStudy/assets/7125622/18cc5231-cc45-4e95-8efe-c4d14a4f352c">
Чтобы при переходе на новый экран, текущий уходил влево, а новый приходил справа. 

3. Когда экран меньше чем нужно, кнопки переносятся на новую строку. Хуже если одна кнопка. Вариантов несколько. Самый простой задать для кнопки максимальное количество строк в названии и способ обрезания невлезающего контента:
```
            android:lines="1"
            android:ellipsize="middle"
```
Еще можно задать
```
android:padding="0dp"
```
Тогда при малых размерах текст будет почти наползать на границы кнопки, но при этом не будет обрезаться сразу (если продолжить уменьшать экран, все равно будет обрезаться). Прочекать можно прямо в студии, двигая уголок:

<img width="600" alt="Screenshot 2024-07-09 at 07 57 47" src="https://github.com/jybo84/AndroidStudy/assets/7125622/f10d4e97-e6d6-466f-b8be-1aaaa32b9ed7">

2024-07-09 04:54 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/ui/RecipesApplication.kt
>  class RecipesApplication : Application() {
так нет вроде, он по прежнему большой.

<img width="508" alt="Screenshot 2024-07-09 at 07 30 13" src="https://github.com/jybo84/AndroidStudy/assets/7125622/d01e7d60-4759-4557-8a77-150e2bccaee1">

Я имел в виду, что нам не нужен тут `recipeModule = RecipeModule()`, он создается сам за счет Hilt

2024-07-09 04:54 UTC, danelyan commented on app/src/main/res/layout/item_recipe.xml
> +        android:background="@color/white"
Это грязный прием. Потом сложно делать темную тему. Отпишу в общем комменте как лучше

2024-07-09 04:54 UTC, danelyan commented on app/src/main/res/values/themes.xml
>          <!-- Customize your light theme here. -->
Это сгенерированный коммент, можно удалить

2024-07-09 04:54 UTC, danelyan commented on build.gradle.kts
> +    id ("com.google.dagger.hilt.android") version "2.51.1" apply false
не исправлено

2024-07-09 13:59 UTC, jybo84 commented on app/src/main/res/values/themes.xml
>          <!-- Customize your light theme here. -->
Исправлено

2024-07-16 06:04 UTC, danelyan approved these changes

2024-07-16 06:33 UTC, merged