Ra 07 implement a basic layout with a list of categories
jybo84/AndroidStudy pull request #5
Opened 2024-03-24 01:50 UTC by jybo84

2024-03-24 19:24 UTC, ievetrov requested changes

2024-03-24 19:24 UTC, ievetrov commented on app/src/main/res/layout/fragment_list_categories.xml
> +            />
Не забывай применять автоформатирование. В том числе и в разметках. Когда все атрибуты стоят на своих местах (в порядковом смысле) - со временем привыкаешь и быстро ориентируешься при их считывании.

2024-03-24 19:24 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    <androidx.recyclerview.widget.RecyclerView
хорошо, но этот тэг давай поместим в лейаут с фрагментом. то по аналогии с контейнером для фрагментов – это контейнер для элементов списка. 

После переноса попробуй растянуть его от шапки до нижней границы контейнера фрагмента.

2024-03-24 19:24 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
а в этом лейауте нужно сверстать именно карточку категории. то есть макет одной карточки, в который позже будут байндиться данные категорий.

2024-03-24 19:24 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +        app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
GridLayoutManager создает сетку. Ее мы использовали на экране с категориями. Обрати внимание, сейчас все элементы располагаются линейно.

2024-03-24 19:24 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    <androidx.recyclerview.widget.RecyclerView
После переноса во фрагмент. Добавь еще в этот тэг атрибут tools:listitem="@layout/item_category"
Так ты увидишь на превьюхе в студии сверстанные карточки категории и как они будут выглядеть в приложении.

Карточку надо сверстать. Представь, что элемент списка – это вот весь данный лейаут. Сделай для него верстку, заполни тестовыми данными в качестве картинки, названия и описания через атрибуты tools.

2024-03-25 13:32 UTC, danelyan requested changes

2024-03-25 13:32 UTC, danelyan commented on app/src/main/res/layout/item_category.xml
> +            android:scaleType="fitXY"
Совсем не похоже на дизайн:

<img width="350" alt="Screenshot 2024-03-25 at 16 27 39" src="https://github.com/jybo84/AndroidStudy/assets/7125622/97618018-20ab-4973-9ef5-29287e134928">

- картинка выглядит растянутой
- отступов не хватает
- шрифт не похож

<img width="292" alt="Screenshot 2024-03-25 at 16 28 51" src="https://github.com/jybo84/AndroidStudy/assets/7125622/40205f8b-576c-4ff9-a11d-4cd71e00c32c">

2024-03-25 13:32 UTC, danelyan commented on app/src/main/res/layout/item_category.xml
> +    android:layout_marginHorizontal="8dp"
кажется не хватает еще вертикального маржина. На превью выглядит вот так:

<img width="300" alt="Screenshot 2024-03-25 at 16 32 10" src="https://github.com/jybo84/AndroidStudy/assets/7125622/3262264c-ba76-477f-b6c1-d30dc1f9d5fd">

Слишком близко друг к другу

2024-03-25 14:19 UTC, danelyan approved these changes
Looks good for me 👍🏻

2024-03-25 14:19 UTC, danelyan commented on app/src/main/res/layout/item_category.xml
> +            android:textColor="#666666"
а для чего хардкодить цвет? Было же нормально

2024-03-25 14:19 UTC, danelyan commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="wrap_content"
match_parent разве плохо работает?

2024-03-25 14:19 UTC, danelyan commented on app/src/main/res/layout/item_category.xml
>              android:id="@+id/textView2"
надо дать более подходящее имя, не дефолтное

2024-03-26 11:13 UTC, merged