RA-08 RecyclerView со списком категорий
jybo84/AndroidStudy pull request #6
Opened 2024-03-26 11:17 UTC by jybo84

2024-03-26 12:02 UTC, jybo84 commented
![image](https://github.com/jybo84/AndroidStudy/assets/135285790/ff7fbfa3-0569-451a-b813-b381de4510a5)

2024-03-26 12:03 UTC, jybo84 commented
Иван, подскажи почему я не могу имплементировать?
И как правильно это делать? В ИДЕЕ есть список вариантов?

2024-03-26 18:40 UTC, ievetrov commented
> Иван, подскажи почему я не могу имплементировать? И как правильно это делать? В ИДЕЕ есть список вариантов?

версии хранятся в корневом каталоге gradle -> libs.versions.toml. вот там и перечислены все версии.

а здесь, на скриншоте перечислены ссылки на конкретные библиотеки. 

то есть получается можно добавить в текущем же синтаксисе библиотеку в либс, но также можно все еще напрямую прописать имплементацию прям в текущем файле. но для этого надо использовать не синтаксис груви (с одинарными кавычками), а синтаксис для kts файлов. поэтому для добавления библиотеки прям тут надо писать так:
`implementation("androidx.recyclerview:recyclerview:1.2.1")`

НО. recyclerview отдельно имплементировать не нужно вообще, так как он есть в стандартной библиотеке уже. так что можно убрать

2024-03-28 18:59 UTC, ievetrovdev requested changes

2024-03-28 18:59 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/tvTitleCategory"
Заголовок карточки и описание расположены с внутренними отступами. Обрати внимание на макет - текст располагается не вплотную к стенкам (паддинги нужны со всех граней)

2024-03-28 18:59 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            tools:text="Рецепты всех \nпопулярных видов \nбургеров" />
Не нужно текст самостоятельно разбивать на строки. Это должно происходить естественным образом по ограничениям контейнера

2024-03-28 18:59 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/recipes.kt
> +            "burger.png",
Зачем поменял местами? В джейсоне порядок другой (есть риск упать проект при парсинге данных)

2024-03-28 18:59 UTC, ievetrovdev commented on app/src/main/java/com/example/androidstudyapp/CategoriesListAdapter.kt
> +class CategoriesListAdapter(private val dataSet: List<Category>) :
по коду отписал в ЛС

2024-03-31 10:49 UTC, ievetrov requested changes

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="156dp"
Ширина должна быть адаптивная. Убираем хардкод

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:fontFamily="@font/montserrat_medium"
все атрибуты оформления текста выносим в стиль

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/recipes.kt
> +            0,
надобавлял лишних категорий. зачем? 
в ТЗ есть конкретный пример

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/CategoriesListAdapter.kt
> +                Log.d("Ошибка.", "Картинка не загрузлась. Не верный адрес")
опечатка

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/java/com/example/androidstudyapp/CategoriesListAdapter.kt
> +                Log.d("Ошибка.", "Картинка не загрузлась. Не верный адрес")
и еще нужен тип лога Error

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    app:cardCornerRadius="@dimen/corner_radius">
Перепроверь отступы у карточки. Список отображается полностью без вертикальных и горизонтальных отсупов сейчас

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    android:layout_margin="8dp"
не забывай выносить размеры в ресурсы

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
>              android:layout_height="130dp"
в ресурсы

2024-03-31 10:49 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:layout_marginTop="8dp"
в ресурсы (проверь остальные места самостоятельно)

2024-03-31 11:17 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/recipes.kt
> +            0,
Исправлено.

2024-03-31 13:28 UTC, jybo84 commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="156dp"
Исправлено

2024-03-31 13:38 UTC, jybo84 commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="156dp"
Для TextView установил значение wight  - wrap_content, тогда у меня текст стал в одно строчку. Не как по ТЗ. Что бы избежать этого я задал для CardView значение - 156.  В итоговом варианте на имитаторе телефона все отражается хорошо, но разметка fragment_list_ categories выглядит, как мне кажется. не правильно.
![Uploading image.png…]()

2024-03-31 13:40 UTC, jybo84 commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="156dp"
Для TextView установил значение wight - wrap_content, тогда у меня текст стал в одно строчку. Не как по ТЗ. Что бы избежать этого я задал для CardView значение - 156. В итоговом варианте на имитаторе телефона все отражается хорошо, но разметка fragment_list_ categories выглядит, как мне кажется. не правильно.

2024-03-31 13:58 UTC, jybo84 commented on app/src/main/java/com/example/androidstudyapp/CategoriesListAdapter.kt
> +                Log.d("Ошибка.", "Картинка не загрузлась. Не верный адрес")
"нужен тип лога Error" - что это значит?

2024-03-31 14:03 UTC, jybo84 commented on app/src/main/res/layout/item_category.xml
> +    app:cardCornerRadius="@dimen/corner_radius">
Здесь не получается. 
На видео которое ты мне присылал, на эмуляторе отдельно видны каждая категория (немного выделяются цветом) и между ними лойаут. У меня почему то кнопки внутри между собой стоят впритык. не получается это исправить.

2024-03-31 14:04 UTC, jybo84 commented on app/src/main/res/layout/item_category.xml
> +    app:cardCornerRadius="@dimen/corner_radius">
Лойаут я специально выделил черным цветом чтоб было лучше видно.

2024-04-01 12:20 UTC, danelyan requested changes

2024-04-01 12:20 UTC, danelyan commented on app/src/main/java/com/example/androidstudyapp/CategoriesListAdapter.kt
> +        return ViewHolder(ItemCategoryBinding.inflate(LayoutInflater.from(parent.context)))
вот тут нужно прокидывать в inflate еще parent:

```Kotlin
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
        return ViewHolder(ItemCategoryBinding.inflate(LayoutInflater.from(parent.context), parent, false))
}
```

Так как ты задаешь отступы при помощи margin:
```
<androidx.cardview.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginHorizontal="8dp"
    android:layout_marginVertical="8dp"
/>
```

Атрибуты layout_marginHorizontal и layout_marginVertical - по сути атрибуты для родителя, чтобы он понимал, как разместить "ребенка" внутри себя. Если при выполнении inflate не указывать parent, то параметры будут проигнорированы

2024-04-02 11:22 UTC, merged